### ISSUE TITLE
ES6 Import version on NPM?

### ISSUE THREAD

**Issue by cparadeise** [crisbeto/angular-svg-round-progressbar#100]
I noticed you have the /build/index.js in the source files on github, but when I npm install, I get a different set of files which excludes the necessary index.js for use with Webpack module loaders. Is there a plan to publish the rest of the repo to npm? Thanks!

**Comment by crisbeto** [comment]
That sounds weird. What version are you installing?

**Comment by cparadeise** [comment]
I just installed it into a new directory, got the right version. My bad! Thanks.
