### ISSUE TITLE
Import not found in my module

### ISSUE THREAD

**Issue by sinzen** [crisbeto/angular-svg-round-progressbar#105]
Hi,

I try to implement a progress bar in my angular2 app.
in your repo i found this line: 
`import { RoundProgressModule } from 'angular-svg-round-progressbar';`

In my module the import can't find this module: `angular-svg-round-progressbar`

I installed with npm the librairies but I can't see an issue..

can you help me?

**Comment by crisbeto** [comment]
Are you sure that your module resolver is pointing to the right place? Also which version are you using?

**Comment by sinzen** [comment]
Thanks for your answer.
What is the resolver à I don't understand..
I'm using the last version of angular 2 and the last version of your repo..
I'm using systemjs in angular 2

**Comment by crisbeto** [comment]
I mean what version of the progress bar module.

**Comment by sinzen** [comment]
Thanks for your message.
The version is 1.0.3

**Comment by sinzen** [comment]
Thanks Crisbeto..
I solved my problem.
Have a nice day.

**Comment by crisbeto** [comment]
In case somebody else runs into it, how did you solve it?
