### ISSUE TITLE
ProgressBar and angular Universal

### ISSUE THREAD

**Issue by sinzen** [crisbeto/angular-svg-round-progressbar#106]
Hi Crisbeto,

In the implementation of a progressBar version 1.0.3.

I try to include the import in a module like this:
`import { RoundProgressModule } from 'angular-svg-round-progressbar/dist/round-progress';`

and I declare in the imports module:
`@NgModule({
  bootstrap: [ AppComponent ],
  imports: [
    ...
    RoundProgressModule,
    ...
  ],
`
I use webpack to complie and I have an Error bellow:

`var BASE = document.head.querySelector('base');`
`ReferenceError: document is not defined`
`[nodemon] app crashed - waiting for file changes before starting...`
Can You help me?

**Comment by crisbeto** [comment]
Yeah, this module expects there to be a DOM. I should be able to switch it over to at least not throw.

**Comment by sinzen** [comment]
How can I fix that?

**Comment by crisbeto** [comment]
You can't, I'll have to fix it on my end and release a fix.

**Comment by crisbeto** [comment]
I've released version `1.0.4` that should fix the errors with Angular Universal.
