### ISSUE TITLE
Gemnasium outdated for angular-1.X

### ISSUE THREAD

**Issue by Adrion** [crisbeto/angular-svg-round-progressbar#108]
Hi 
I have a false-positive outdated dependency with Angular 1.6.1 app on Gemnasium : 

<img width="1029" alt="Gymnasium" src="https://cloud.githubusercontent.com/assets/5418815/22584904/4fe749bc-e9f5-11e6-8a41-39000401fe8a.png">

With a seperate bower repo, It will resolve the Gemnasium state. In this case the lib is not outdated, it will not change for AngularJS.

Can you please create a angularjs-svg-round-progressbar bower dep ?

**Comment by crisbeto** [comment]
I'm not keen on having to manage multiple repos for the same project. I'm also not sure how Bower picked up the 1.0.4 version, but I removed the bower.json in 1.0.0 and haven't published anything to it.

**Comment by Adrion** [comment]
I have no issue with my deps manager but I's sad to have an out-dated badge just for this.

It may be the same project but A1 & A2 are totally different so I thought 2 bower repos is not that bad.

**Comment by crisbeto** [comment]
I get your point, but that would mean asking people to install from a different place and I'm not exactly sure how it would work out with Bower picking up the new repo. It's a lot easier to set your dependencies to install versions < 1.0.0, even though Gemnasium and similar may consider it outdated.
