### ISSUE TITLE
How do I import `RoundProgressConfig`  angular2/ionic2

### ISSUE THREAD

**Issue by mixersoft** [crisbeto/angular-svg-round-progressbar#109]
This is what I have, and it seems to work at runtime, but I always get a typescript error

```
/// <reference path="../../node_modules/angular-svg-round-progressbar/dist/round-progress.d.ts" />

import { Component } from '@angular/core';
import { Platform } from 'ionic-angular';
import { StatusBar, Splashscreen } from 'ionic-native';
import { RoundProgressModule, RoundProgressConfig } from 'angular-svg-round-progressbar';

import { TabsPage } from '../pages/tabs/tabs';

@Component({
  templateUrl: 'app.html',
  providers: [RoundProgressConfig]
})
export class MyApp {
  rootPage = TabsPage;

  constructor(
    platform: Platform
    , private _roundProgressConfig: RoundProgressConfig
  ) {
    _roundProgressConfig.setDefaults({
      rounded: true,
      responsive: true
    })
  }
}
```

**Comment by crisbeto** [comment]
Can you post the error that you're getting?

**Comment by mixersoft** [comment]
at runtime it seems to work. I'm just getting a typescript compiler error: `[ts] Cannot find name 'RoundProgressConfig'` in the constructor param.  I am using the following `tsconfig.json` which comes from the standard `ionic2` project skeleton.

```
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2015"
    ],
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "target": "es5",
    "types": [
      "jasmine"
    ]
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": false,
  "atom": {
    "rewriteTsconfig": false
  }
}
```

`/// <reference path="` doesn't seem to fix it. `jasmine` has a definition file in `./node_modules/@types/jasmine/index.d.ts`

**Comment by crisbeto** [comment]
My guess is that the path isn't being resolved properly at runtime. Can you check your Dev tools' "Network" tab if the request 404s?

**Comment by mixersoft** [comment]
nevermind. I think it's a typescript error based on the project config. when I use ChromeDevTools to inspect,`RoundProgressConfig` is properly injected.

**Comment by crisbeto** [comment]
Alright, I'll close the issue in that case. Thanks for following up.
