### ISSUE TITLE
Should support provider for default values

### ISSUE THREAD

**Issue by Kuzmin** [crisbeto/angular-svg-round-progressbar#11]
I think it would be neat if there was a way to be able to set default values for this on the whole app. At least in our case, it should look identical each time we use it, this would save a lot of time!

**Comment by crisbeto** [comment]
Good idea, I'll take a look.

**Comment by crisbeto** [comment]
@Kuzmin Done. Now you can use the `roundProgressConfig` constant to edit the default values for everything except `current`. You can refer to the [0.2.2 release](https://github.com/crisbeto/angular-svg-round-progressbar/releases/tag/0.2.2)

**Comment by Kuzmin** [comment]
Awesome! Thanks for the quick response!
