### ISSUE TITLE
Parser Error: Unexpected token # at column 1 in [#45ccce] 

### ISSUE THREAD

**Issue by EddyTheDove** [crisbeto/angular-svg-round-progressbar#110]
Using ionic2. Everything works fine until I want to change either `color` or `background`. It returns following error: Parser Error: Unexpected token # at column 1 in [#45ccce] .

I just copied pasted the example in the demo. If I remove color and background, everything else works perfect.

**Comment by crisbeto** [comment]
Looks like I didn't try out my own example. Either using `color="#45ccce"` or `[color]="'#45ccce'"` should work.

**Comment by EddyTheDove** [comment]
Thank you very much @crisbeto
