### ISSUE TITLE
RoundProgressModule is not an NgModule

### ISSUE THREAD

**Issue by NickMcBurney** [crisbeto/angular-svg-round-progressbar#112]
Hi,

Im trying to use this within an angular-cli project, I have installed via npm and imported into my app:

```
import { RoundProgressModule } from 'angular-svg-round-progressbar';
@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    BrowserModule,
    FormsModule,
    ReactiveFormsModule,
    HttpModule,
    routing,

    DashboardModule,
    RoundProgressModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})

export class AppModule { }
```

but when I try and either build or serve the app using `ng serve` I get an error: 

>  ERROR in RoundProgressModule is not an NgModule

**Comment by nitheshsd123** [comment]
Even me also getting same error. Can anyone help me out please

**Comment by crisbeto** [comment]
What version are you guys using?

**Comment by nitheshsd123** [comment]
I am using "1.0.5" version

**Comment by crisbeto** [comment]
Alright, then it's related to the issues that people are reporting at https://github.com/crisbeto/angular-svg-round-progressbar/issues/65. I need to switch to using ngc.

**Comment by nitheshsd123** [comment]
So when can we except ?

**Comment by crisbeto** [comment]
I'm not trying to give any guarantees since I'm pretty busy. I'll try to carve out some time this week.

**Comment by NickMcBurney** [comment]
Im also on V1.0.5, thanks @crisbeto

**Comment by CarlosTorrecillas** [comment]
thanks for this @crisbeto . Much appreciated if you could make the change this week 👍

**Comment by crisbeto** [comment]
I've been trying some stuff out. It would be really helpful if you guys could try this out and let me know if it fixes it for you: https://github.com/crisbeto/angular-svg-round-progressbar/issues/65#issuecomment-286441243

**Comment by CarlosTorrecillas** [comment]
Should we expect to have a umd.js on that zip?

**Comment by crisbeto** [comment]
No, it only points the `main` to `index.js` which exposes the module.

**Comment by CarlosTorrecillas** [comment]
That's what I thought. I am now referencing the `index.js` on the systemjs.config.js and it's not able to load the app: 

> Error: Fetch error: 404 Not Found Instantiating http://localhost:10100/node_modules/angular-svg-round-progressbar/dist/round-progress.component

**Comment by LucasKubicki** [comment]
![error](https://cloud.githubusercontent.com/assets/16726752/24005511/841b2a7a-0a69-11e7-9dc2-018fad3af195.png)
I have that error if its can help

**Comment by EmanuelCarneiro** [comment]
hi guys, 

I fixed this by copying the files in the source code (in the repo) and importing the Module from the local files rather than the node_modules.

Is not ideal but it solves the problem for now.

**Comment by acassan** [comment]
Hello,

Have you plan to commit fix on master ? :-)

Thanks

**Comment by crisbeto** [comment]
I've released 1.0.6 which includes the new build output. Also here's Angular's "getting started" app which has imported the round progress module.
[toh-3.zip](https://github.com/crisbeto/angular-svg-round-progressbar/files/870447/toh-3.zip)

**Comment by vandres** [comment]
1.0.6 works for me with Ionic 2 in production mode

**Comment by crisbeto** [comment]
@NickMcBurney can you confirm whether it works with 1.0.7?

**Comment by katestearns-suplari** [comment]
I'm getting the same issue - I tried the npm install that was recommended in the comment with no luck. Any updates on what we need to do?

**Comment by crisbeto** [comment]
I was under the impression that it works as expected now. Can you post an example @katestearns-suplari?

**Comment by katestearns-suplari** [comment]
I uninstalled and reinstalled and it is now working
