### ISSUE TITLE
How to initialise in afterviewinit?

### ISSUE THREAD

**Issue by puneetsngh** [crisbeto/angular-svg-round-progressbar#122]
I want to start progressbar animation when it came to viewport. Currently, it starts as the page load. Is there a way to start animation in afterviewinit?

**Comment by crisbeto** [comment]
You can have your value be 0 in the beginning and assign the `current` value at a later point.

**Comment by puneetsngh** [comment]
thanks, yeah that works actually I was using it inside the jquery function and I forgot about `this`
