### ISSUE TITLE
TypeError: e.$watchGroup is not a function

### ISSUE THREAD

**Issue by raghuraju** [crisbeto/angular-svg-round-progressbar#124]
Angular version: 1.2.x
Round progress bar version: 0.4.8

Can it be solved without having to upgrade Angular to 1.3?

**Comment by crisbeto** [comment]
Not really @raghuraju. Alternatively, you can downgrade to a version of the progress circle that was before 1.3. I don't remember exactly which, but I believe that the ones around 0.3.0 should support it.
