### ISSUE TITLE
Unexpected value 'undefined' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by epot** [crisbeto/angular-svg-round-progressbar#128]
Hello,

I am trying to follow the readme steps (I am using SystemJS as module loader) but I got this error when importing the RoundProgressModule:
    
    import { RoundProgressModule } from 'angular-svg-round-progressbar';

 I do not really know how to debug what is happening.
I depend on Angular 4.1.2.

Any idea?

**Comment by crisbeto** [comment]
That error usually happens if it didn't manage to find the class that you're importing (even though it loaded the file).

**Comment by epot** [comment]
Ok. I did import the umd file, I wonder how the class cannot be found afterwards.

**Comment by crisbeto** [comment]
I think the UMD file might not work correctly at the moment (I'll need to spend a bit more time on the build process to get it working). Can you try using the index file instead?

**Comment by epot** [comment]
Do you mean putting this:
    
    'angular-svg-round-progressbar': 'npm:angular-svg-round-progressbar/dist/index.js',

in my systemjs.config.js file? Cause I then get 404 errors for others angular-svg-round-progressbar files (like round-progress.config). Sorry I am a newbie in all those things (angular2, systemJS...), I was hoping it would work out of the box :-).

**Comment by crisbeto** [comment]
Yes, pointing it to the `index.js` should do it.

**Comment by epot** [comment]
Unfortunately I am getting several 404:

Failed to load resource: the server responded with a status of 404 ()
localhost/:22 Error: Fetch error: 404 
  Instantiating https://localhost/libs/angular-svg-round-progressbar/dist/round-progress.config

**Comment by crisbeto** [comment]
Hmm, weird thing about that URL is that it's trying to load it without the `.js` extension. You can see the SystemJS config I have for the demo app for reference: https://github.com/crisbeto/angular-svg-round-progressbar/blob/master/demo/systemjs.config.js#L17

**Comment by epot** [comment]
Awesome, it works fine by adding a defaultExtension. I will check later if you fix the UMD file, but I can use the component so it is all good for now!
