### ISSUE TITLE
Support latest AngularJS stable (v1.3.14)

### ISSUE THREAD

**Issue by egel** [crisbeto/angular-svg-round-progressbar#13]
Consider to support latest version 1.3.14 of angular in bower.json

**Comment by crisbeto** [comment]
I haven't really tried it with the latest Angular version, but there's no reason it wouldn't work. This was the current version when I released it.

**Comment by crisbeto** [comment]
Can confirm that it works fine, did a minor release to bump the version https://github.com/crisbeto/angular-svg-round-progressbar/releases/tag/0.2.5
