### ISSUE TITLE
Error when Max = 0

### ISSUE THREAD

**Issue by michel-soares** [crisbeto/angular-svg-round-progressbar#130]
Erro in console:
 Error: <path> attribute d: Expected number, "M NaN NaN A 117.5 …". 
When Max value is 0 (zero). 
I need to implement values like 10/0 and round is all completed. When nothing were expected and 10 were found.

In sample page http://crisbeto.github.io/angular-svg-round-progressbar/ put the value 10 and max 0 and   console show a lot of errors.

![image](https://user-images.githubusercontent.com/14979508/29317092-de1e7e10-81a0-11e7-81a2-00f3a90edbb0.png)

**Comment by michel-soares** [comment]
#132

**Comment by crisbeto** [comment]
Closing as fixed by https://github.com/crisbeto/angular-svg-round-progressbar/pull/132.
