### ISSUE TITLE
Angular 1.x version only supports Angular 1.3+

### ISSUE THREAD

**Issue by LucasMetal** [crisbeto/angular-svg-round-progressbar#133]
Hi!

Due to the usage of $watchGroup, the `angular-1.x` branch only supports Angular 1.3 or above.

This made me lose a couple of hours as I'm using Angular 1.2.8.
Could you please update the readme to state the minimum version or change the implementation so it really supports Angular 1.x?

Thanks a lot!
Great directive!

**Comment by crisbeto** [comment]
Fixed in af1b838b3673fbab9feb61458606730dd6cca36d.

**Comment by LucasMetal** [comment]
Wow, that was fast!
Thanks!!
