### ISSUE TITLE
Error: <path> attribute d: Expected number, "M NaN NaN A 27.5 2…".

### ISSUE THREAD

**Issue by Eashwarswamy** [crisbeto/angular-svg-round-progressbar#136]
Hi,

I am trying to use the 'angular-svg-round-progressbar'

Not able to assign the JSON dynamic value to <round-progress [max]="{{item.number}}">

could you please help me, how do we config the dynamic values.

**Comment by crisbeto** [comment]
You're supposed to use it like this `<round-progress [max]="item.number">`.

**Comment by Eashwarswamy** [comment]
Hi Crisbeto,

Thanks for very quick help.

Issue is solved now, I am able to draw the circles now but **max** and **current** values are not displaying the **center** of the circle.

Below is my actual code.

  _<round-progress [radius]="30"  [rounded]="true" [stroke]="5"  [max]="item.totJobs" [current]="item.jobsDead"
                     [color]="item.colorHighlight"
                     [background]="'#84F5D5'" ></round-progress>_

Could you please let me know am I missing something here.

Thanks,
Eashwar

**Comment by crisbeto** [comment]
This module doesn't support rendering the text automatically on purpose, because text can be represented in a lot of different ways and it's relatively simple to do it yourself. You can check out the demo to see how it was done there: https://github.com/crisbeto/angular-svg-round-progressbar/tree/master/demo

**Comment by Eashwarswamy** [comment]
Hi Crisbeto,

Thanks again, It was my mistake I Just concentrated on the options.

I am able to display the content text inside the circle.

Hence I am closing the ticket.

**Comment by jasonz1987** [comment]
i got the same error even i used [max].

> Error: <path> attribute d: Expected number, "M NaN NaN A 72.5 7…".

i also update the latest version 1.1.1,but it still doest not work.
