### ISSUE TITLE
Add ability to change the inner circle background color

### ISSUE THREAD

**Issue by datencia** [crisbeto/angular-svg-round-progressbar#138]
Hi @crisbeto, Very nice work with this library.

It would be great if we could change the inner circle background color. If you agree, I can send a PR with this change.

**Comment by datencia** [comment]
I forgot to mention how: "through the component's options"

**Comment by crisbeto** [comment]
I'm not sure it's really necessary, You can easily target the element with CSS.

**Comment by datencia** [comment]
I'm not really sure too. In my case, I need to change the background color based on ranges of the current value.

You can consider it as syntactic sugar, a simple way to change the background color without the need to specify a custom CSS class.

For example, you could also use CSS classes to define the color for the circle background & foreground and however, it is possible to configure these properties via `color` & `background` options.

I will try adding custom CSS classes using the `ngClass` directive to define every range of colors.

Thank you very much for replying quickly.
