### ISSUE TITLE
Percentage

### ISSUE THREAD

**Issue by rhsu0268** [crisbeto/angular-svg-round-progressbar#145]
I want to add the current value and total value to the progress. When we want to get at the "current" value and "max" in the html, how do we get ahold of them?

Many thanks in advance!

**Comment by crisbeto** [comment]
It's unsupported by default, but you can do it yourself by adding the value on top of the circle. You can refer to this comment to see how: https://github.com/crisbeto/angular-svg-round-progressbar/issues/55#issuecomment-173504646
