### ISSUE TITLE
It's work for Ionic 3?Runtime Error Unexpected value 'RoundProgressService' imported by the module 'AppModule'. Please add a @NgModule annotation.

### ISSUE THREAD

**Issue by AltRoot17** [crisbeto/angular-svg-round-progressbar#147]
Im try to added this **Ionic 3** project, But its not working 
```
Runtime Error
Unexpected value 'RoundProgressService' imported by the module 'AppModule'. Please add a @NgModule annotation.
```

**Comment by ianlintner-wf** [comment]
Version 1.1.0 supports angular 4. I think the current master/head version is for angular 5.

https://github.com/crisbeto/angular-svg-round-progressbar/releases/tag/1.1.0

For your install command use this instead for now, but will need to update when Ionic moves to Angular 5.

```bash
npm install angular-svg-round-progressbar@1.1.0 --save
```

**Comment by crisbeto** [comment]
If you're on Angular 4, you should install version 1.1.0, whereas if you're on Angular 5 you should use 1.2.1.
