### ISSUE TITLE
Error: Unexpected value 'undefined' imported by the module 'AppModule'

### ISSUE THREAD

**Issue by markkesty** [crisbeto/angular-svg-round-progressbar#148]
I started having a problem with this component recently when I upgraded from Angular 2 to Angular 4. The issue didn't start immediately but waited until I had deleted my node_modules folder and then ran npm install again.

I created a brand-new shiny Plunker and did nothing but add this component to it and I'm getting the above error. If you remove the RoundProgressModule from the imports section in app.ts, the Plunker loads just fine. However, if you add it back in, you'll see the above error in the console.

In general, it would be helpful to provide a demo using Plunker so people could start with a working version and see where they went wrong. 

Here is the link to the Plunker: https://plnkr.co/edit/uHEakUZNUhjszDyRdCBm?p=preview

**Comment by crisbeto** [comment]
Should be fixed in the 1.2.1 release.
