### ISSUE TITLE
Small ui bug - progress bar does not fully cover background

### ISSUE THREAD

**Issue by gnesher** [crisbeto/angular-svg-round-progressbar#150]
![bug](https://user-images.githubusercontent.com/1402060/33270895-3cef7374-d38e-11e7-8acd-2e8ac7fcbb49.PNG)

In Chrome (latest) there is a small outline around the progress bar (set by color) which reveals the background. Offsetting either by 1px solves this, but I'm not sure if that's the right solution.

I've tried different border widths, same problem (but less visible if the border is thinner)

**Comment by crisbeto** [comment]
This is a browser rendering issue. I asked a question about it on StackOverflow a while ago, but the solution isn't pretty or performant. See https://stackoverflow.com/questions/33599349/svg-stacked-elements-color-overlap
