### ISSUE TITLE
Not working on Angular 5.0.3

### ISSUE THREAD

**Issue by SaadAhmedSiddiqui** [crisbeto/angular-svg-round-progressbar#152]
I am having this issue breaking the app
Uncaught Error: Unexpected value 'RoundProgressModule' imported by the module 'AppModule'. Please add a @NgModule annotation
just because of this component I am unable to upgrade to angular 5.0.3
if it exist, I will have no choice but to discontinue using it

**Comment by crisbeto** [comment]
Should be fixed in the 1.2.1 release.
