### ISSUE TITLE
Angular 4 to 5 migration issue: No provider for NgZone!

### ISSUE THREAD

**Issue by mattiLeBlanc** [crisbeto/angular-svg-round-progressbar#154]
`ERROR Error: Uncaught (in promise): Error: StaticInjectorError[NgZone]: 
  StaticInjectorError[NgZone]: 
    NullInjectorError: No provider for NgZone!`

This is what I am getting after migrating from 4.2.4 to 5.0.5.
When I comment my round-progress tag, the page will run fine. I thought it was related to a `httpClient` module (because of google search on error)  I but it's not, I guess.

I did build a new angular CLI project, and added the round-progress in and it worked fine.
So maybe something went wrong during the update or it is something else.

I will try copying over my code from my current project to the new cli starter.

```
"dependencies": {
    "@angular/animations": "^5.0.0",
    "@angular/common": "^5.0.0",
    "@angular/compiler": "^5.0.0",
    "@angular/core": "^5.0.0",
    "@angular/flex-layout": "^2.0.0-beta.10-4905443",
    "@angular/forms": "^5.0.0",
    "@angular/http": "^5.0.0",
    "@angular/platform-browser": "^5.0.0",
    "@angular/platform-browser-dynamic": "^5.0.0",
    "@angular/platform-server": "^5.0.0",
    "@angular/router": "^5.0.0",
    "angular-svg-round-progressbar": "^1.2.1",
    "core-js": "^2.4.1",
    "jsrsasign": "^8.0.4",
    "lodash": "^4.17.4",
    "rupture": "^0.6.2",
    "rxjs": "^5.5.2",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "^1.5.5",
    "@angular/compiler-cli": "^5.0.0",
    "@angular/language-service": "^5.0.0",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "^4.0.1",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "^2.4.2"
  }
```

**Comment by mattiLeBlanc** [comment]
Moving my SRC folder over to the new NG CLi generated project fixed the issue.
Not sure what went wrong in the migration..

**Comment by FlawaCLV** [comment]
Does anyone has this issue? I'm struggling with, can't find a way to run my app on Angular 5.2.0

**Comment by mozgor** [comment]
Facing the same issue here, would appreciate a lot any detail which could led to a solution.

**Comment by mattiLeBlanc** [comment]
Have you tried updating your NG CLI and create a new project and copy over your files?
That was the solution for me.

**Comment by FlawaCLV** [comment]
I've tried but didn't do the trick. I've been developing on Angular 2 since the beginning and it's the first time that I'm THAT stuck...

**Comment by mattiLeBlanc** [comment]
Was your code base Angular 2 or Angular 4? Maybe it became incompatible .

Try to copy over a small part into a fresh install and see if it runs, then
add the rest in chunks?
Know it sucks but only then will you find which part of your code might be
the culprit

**Comment by FlawaCLV** [comment]
I switched from Angular 4.3

**Comment by DotNetPart** [comment]
I intermittently get the same issue.
