### ISSUE TITLE
If current > max, then current is set to max

### ISSUE THREAD

**Issue by GedRap** [crisbeto/angular-svg-round-progressbar#16]
Example:

```html
<div
          round-progress
          max="dailyTarget"
          current="consumption"
          color="{{ (consumption / dailyTarget < 0.75) ? '#F0B840' : '#6C3' }}"
          bgcolor="#eaeaea"
          radius="110"
          stroke="20"
          semi="true"
          rounded="false"
          iterations="50"
          animation="easeInOutQuart">
</div>
```

```javascript
$scope.consumption = 5;
$scope.dailyTarget = 3;
```

`$scope.consumption` will be set to 3.

I am not exactly sure whether it's a bug or intended behavior. On one hand, it makes sense that `current` is set to the widget current value even if it's not the original value. However, the widget is responsible for  display only and it's not updating or pulling data from anywhere so I'd call it unexpected behavior.

If @crisbeto agrees that it's a bug, I'd like to fix it and submit a PR.

**Comment by crisbeto** [comment]
Its definitely intended behaviour, here's the place in the source where the assignment is happening https://github.com/crisbeto/angular-svg-round-progressbar/blob/master/src/roundProgress.js#L77. If its an issue there can be an option to disable this.

**Comment by GedRap** [comment]
Thanks for clarifying! I guess there's no need for an option as it's easy to deal with from the application side, just a documentation update might be useful as it's not obvious :)

**Comment by crisbeto** [comment]
Done.
