### ISSUE TITLE
Want multiple progress bar in single page but in different color

### ISSUE THREAD

**Issue by sidkasundra** [crisbeto/angular-svg-round-progressbar#162]
how can i set particular color for particulate progress bar..
whenever i change the color that is in round-progress.config.js but it change the color of both the progress bar..
Thank you

**Comment by crisbeto** [comment]
The settings in the `round-progress.config` apply to all progress bars. If you want to set the color only for a particular component, you can pass it in instead:

```html
<round-progress color="red"
</round-progress>
```

**Comment by sidkasundra** [comment]
ow,,,it works..silly 
i tried through style that not work for me
[<round-progress style="color:#ff0000" [current]="current" [max]="max"></round-progress>
]
Thanks
