### ISSUE TITLE
Noob help

### ISSUE THREAD

**Issue by CodeWithClass** [crisbeto/angular-svg-round-progressbar#166]
I've gotten the default to load in my application but I cant figure out how to pass values to change the progress bar. 

The only way I am currently able to is by manually changing the HTML..

**Comment by crisbeto** [comment]
It's hard to tell what might be wrong without any code samples, but you can take a look at the source code for the demo page to see how it's been implemented there. https://github.com/crisbeto/angular-svg-round-progressbar/tree/master/demo
