### ISSUE TITLE
Counter Clockwise animation

### ISSUE THREAD

**Issue by tgrant59** [crisbeto/angular-svg-round-progressbar#17]
Is it possible to animate the circle counter clockwise?

**Comment by crisbeto** [comment]
It wasn't possible, now it is. Refer to the [0.2.6 release](https://github.com/crisbeto/angular-svg-round-progressbar/releases/tag/0.2.6 release).

**Comment by tgrant59** [comment]
Awesome! Another feature to think about (I don't actually need it personally) would be starting the animation at any point on the circle. This was huge timesaver for me
