### ISSUE TITLE
Error importing the module in Angular 6

### ISSUE THREAD

**Issue by anidraik** [crisbeto/angular-svg-round-progressbar#171]
Hi - getting the following error when trying to import the module:

@NgModule({
  imports: [RoundProgressModule]
})

`ERROR in ./node_modules/angular-svg-round-progressbar/node_modules/@angular/common/@angular/common.es5.js
Module build failed: Error: ENOENT: no such file or directory, open '/Website/website-angular6/website-angular6/node_modules/angular-svg-round-progressbar/node_modules/@angular/common/@angular/common.es5.js'
ERROR in ./node_modules/angular-svg-round-progressbar/node_modules/@angular/core/@angular/core.es5.js
Module build failed: Error: ENOENT: no such file or directory, open '/Website/website-angular6/website-angular6/node_modules/angular-svg-round-progressbar/node_modules/@angular/core/@angular/core.es5.js'
`

Running Angular 6.0.3 and using angular-svg-round-progressbar@2.0.0

Any thoughts?

**Comment by crisbeto** [comment]
It looks like an issue with your build setup.

**Comment by anidraik** [comment]
I'll take a look. Thanks!
