### ISSUE TITLE
update the dependencies to version 7 of angular

### ISSUE THREAD

**Issue by DuncanFaulkner** [crisbeto/angular-svg-round-progressbar#175]
Is is possible to update the dependencies to version 7 of angular?

**Comment by DuncanFaulkner** [comment]
Any update on this - has this project gone cold last update May 2018?

**Comment by crisbeto** [comment]
The project is being maintained, I just haven't had the time to bump the version and do a release. Also there aren't any changes between Angular 6 and 7 that would break the component.

**Comment by moscoso** [comment]
This would be great so that it would stop giving peer dependency warnings.

**Comment by DuncanFaulkner** [comment]
this can probably be closed now
