### ISSUE TITLE
Update to angular 8 breaks with AOT build.

### ISSUE THREAD

**Issue by sliceofbytes** [crisbeto/angular-svg-round-progressbar#188]
Any angular 8 AOT builds with the new version break with errors.

Confirmed with minimal example.

ERROR TypeError: i1.RoundProgressService is not a constructor

**Comment by crisbeto** [comment]
I've released 3.0.1 that should resolve it.

**Comment by sliceofbytes** [comment]
Thank you for addressing this so quickly!
