### ISSUE TITLE
Won't compile with Angular 8 and Ivy

### ISSUE THREAD

**Issue by bikeguy** [crisbeto/angular-svg-round-progressbar#190]
When compiling with Angular 8 with Ivy turned on I am getting the following error:
There is no format with import statements in '/node_modules/angular-svg-round-progressbar' entry-point

And the ng serve build fails. 

Using version 3.0.1
Works fine with Ivy turned off.

Thanks!

**Comment by Phmager** [comment]
I have the same problem. See here: https://github.com/text-mask/text-mask/issues/930
and here: https://github.com/angular/angular/issues/29564

**Comment by MosquitoD4K** [comment]
When I change the package.json to this, the compiler (npx ivy-ngcc) will go through:

![image](https://user-images.githubusercontent.com/7332498/59549305-e9463880-8f5b-11e9-97cb-7d6e1c593f92.png)

**Comment by crisbeto** [comment]
As of version 5.0.1 the project is using the standard Angular Package Format which should resolve this issue.
