### ISSUE TITLE
upgrading to version 10 Angular

### ISSUE THREAD

**Issue by DuncanFaulkner** [crisbeto/angular-svg-round-progressbar#204]
Hi,

I upgraded an angular project from v9 to v10 and I've updated RoundProgressModule to v4 but I'm getting this error.

ERROR in Unexpected value 'RoundProgressModule in /home/duncan.faulkner/development/integra-frontend/node_modules/angular-svg-round-progressbar/dist/index.d.ts' imported by the module 'VendorModule in /home/duncan.faulkner/development/integra-frontend/apps/integra-frontend/src/app/shared/vendor.module.ts'. Please add a @NgModule annotation.

I've also tried to run the demo, but this just sits on the loading page with the error "invalid character < in systemjs"

version 3.0.1 does work, but complains about 

cat of index.d.ts file
import * as i0 from "@angular/core";
import * as i1 from "./round-progress.component";
export declare class RoundProgressModule {
    static ɵmod: i0.ɵɵNgModuleDefWithMeta<RoundProgressModule, [typeof i1.RoundProgressComponent], never, [typeof i1.RoundProgressComponent]>;
    static ɵinj: i0.ɵɵInjectorDef<RoundProgressModule>;
}
export * from './round-progress.component';
export * from './round-progress.service';
export * from './round-progress.ease';
export * from './round-progress.config';

**Comment by jurienhamaker** [comment]
Why was this closed?
Did you resolve this @DuncanFaulkner ? Because I am still getting this error.

**Comment by DuncanFaulkner** [comment]
No I didn't
