### ISSUE TITLE
proposed new library

### ISSUE THREAD

**Issue by DuncanFaulkner** [crisbeto/angular-svg-round-progressbar#205]
Hi Kristiyan

I've created a branch (createLibrary) on a fork of your repo. I've updated it to be a new angular library project. The component itself hasn't changed just the project structure around it.

There is still a bunch of things to do, tests, add an ng add schema etc..so this isn't merge ready at this moment in time.

So just really seeing if this is worth pursuing further - happy to discuss further if you would like.

Cheers
Duncan

**Comment by crisbeto** [comment]
"new library" sounds a little vague, but I'd be interested in look into it. I've wanted to switch to `ng-packagr` for a while now since this custom Gulp setup isn't very sustainable (e.g. it doesn't work with newer Node versions without some Yarn hacks), but I just haven't had the time. I think the biggest unknown is how the demo page and the development workflow will be set up.

**Comment by DuncanFaulkner** [comment]
Yes sorry it could have been a little more descriptive.

If you have a look at the branch I created (it's not merge ready) but it's basically an angular project with the your progressbar component moved to the projects section. I used the ngneats lib tool to create the library setup as this projects takes care of the boiler plate stuff, including all the semantic versioning, and automatic generation of change logs based on commits.

I was going to set up an ng schema so the package could be installed via an "ng add round-progressbar" (for example).

the demo page is currently on the app.component.html of the angular application, though this could be expanded to be the full demo.

**Comment by DuncanFaulkner** [comment]
Hi Kristiyan

I've updated the createLibrary branch to include the demo project and I've added ng add @cristbeto/round-progress as a schema. As I mentioned in the PR I've not tested the ng add as yet, I think this would put round-progress as an npm package under my NPM account and I didn't want to start to confuse people thinking this was the latest update, when it should update your NPM repo

**Comment by DuncanFaulkner** [comment]
would you like any help closing the outstanding issues out?

**Comment by DuncanFaulkner** [comment]
I'm sure you already know about this but I've just come across this article on deploying Angular apps to gh pages. This would probably work for your demo, in case you are not aware of it thought this might help with this project.

https://fluin.io/blog/host-your-angular-project-with-github

**Comment by crisbeto** [comment]
Yep, I'm aware of it. This is how I've been hosting the project until now.

**Comment by DuncanFaulkner** [comment]
Thought you might be aware of it.
