### ISSUE TITLE
Question: Does v4 break on Angular 9?

### ISSUE THREAD

**Issue by wcjord** [crisbeto/angular-svg-round-progressbar#206]
I know the peer dependency is for Angular 10 but does it break on Angular 9? Is there a version of the progressbar that would work for 9?

**Comment by crisbeto** [comment]
It just bumps the peer dependency, but it should work on pretty much any version of Angular after 2.

**Comment by wcjord** [comment]
Awesome! Thank you.

**Comment by nelson6e65** [comment]
Could you add Angular => 9 instead of fixed to 10 peer dependency?

So, I'm getting a bunch of warnings:
```
npm WARN angular-svg-round-progressbar@4.0.0 requires a peer of @angular/core@^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-svg-round-progressbar@4.0.0 requires a peer of @angular/common@^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-svg-round-progressbar@4.0.0 requires a peer of core-js@^2.4.1 but none is installed. You must install peer dependencies yourself.
```

And idk if I can use version 5 neither:
```
npm WARN angular-svg-round-progressbar@5.0.2 requires a peer of @angular/core@^10.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-svg-round-progressbar@5.0.2 requires a peer of @angular/common@^10.0.0 but none is installed. You must install peer dependencies yourself.
```

I didn't find a breaking in change log or something. 😭

**Comment by crisbeto** [comment]
I expect that it'll work down to version 2.0 since it's only using some very basic framework features and the rest is DOM manipulation and math. I've been bumping up the version as people have requested it and as new version have been released.

**Comment by nelson6e65** [comment]
Oh! Nice! Thanks.
