### ISSUE TITLE
[^4.0.0] [Angular 10.0.8] Production build isue. Related to #204

### ISSUE THREAD

**Issue by jurienhamaker** [crisbeto/angular-svg-round-progressbar#208]
Unexpected value 'RoundProgressModule' imported by the module 'UiModule'. Please add a @NgModule annotation.

**ng version**

    
         _                      _                 ____ _     ___
        / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
       / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
      / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
     /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                    |___/
        
    
    Angular CLI: 10.0.8
    Node: 12.18.3
    OS: linux x64
    
    Angular: 10.0.14
    ... animations, common, compiler, compiler-cli, core, forms
    ... platform-browser, platform-browser-dynamic
    Ivy Workspace: Yes
    
    Package                           Version
    -----------------------------------------------------------
    @angular-devkit/architect         0.1000.8
    @angular-devkit/build-angular     0.1000.8
    @angular-devkit/build-optimizer   0.1000.8
    @angular-devkit/build-webpack     0.1000.8
    @angular-devkit/core              10.0.8
    @angular-devkit/schematics        10.0.8
    @angular/cli                      10.0.8
    @ngtools/webpack                  10.0.8
    @schematics/angular               10.0.8
    @schematics/update                0.1000.8
    rxjs                              6.5.5
    typescript                        3.9.7
    webpack                           4.43.0
        
    Done in 0.51s.

**yarn list angular-svg-round-progressbar**

    yarn list v1.22.4
    warning Filtering by arguments is deprecated. Please use the pattern option instead.
    └─ angular-svg-round-progressbar@4.0.0
    Done in 1.08s.

**Comment by jurienhamaker** [comment]
It was an error with storybook not running ngcc

**Comment by DuncanFaulkner** [comment]
I'm not running storybook, may be I just need to run the ngcc?
