### ISSUE TITLE
Filling color in case of 0 current value

### ISSUE THREAD

**Issue by samgic** [crisbeto/angular-svg-round-progressbar#218]
Select rounded as true and provide current value 0, it will show the wrong chart, i mean in case of 0 it shouldn't fill the color in half circle.
Please check the attached screenshot
![Screenshot_20210321-174046](https://user-images.githubusercontent.com/57262776/111907063-21ea3e80-8a6d-11eb-86ff-72e02fffbd23.jpg)

**Comment by crisbeto** [comment]
Fixed in version 7.0.0.
