### ISSUE TITLE
An option to fit the circle into the parent container

### ISSUE THREAD

**Issue by bisubus** [crisbeto/angular-svg-round-progressbar#22]
Can we make it? I found that valid use case is responsive layout.

I think it should essentially do `viewBox` instead of `width` and `height` (not sure if there's a reason to use it with the option switched off). I can PR my own fix, once I will merge it with latest commits.

**Comment by crisbeto** [comment]
I'm not sure I understand the use case. Do you want the SVG element to fill up its parent?

**Comment by bisubus** [comment]
That's right. So css classes could handle the dimensions without js hacks.  It required something like `viewBox = 0 0 size size` and `width: 100%` to do that in my case.

**Comment by crisbeto** [comment]
Oh nice that works quite well. Initially nothing happened since I didn't anticipate that the viewBox attribute is case-sensitive. 
Only thing is that I'm not a big fan of is the requirement to manually add a class to your stylesheet. I'd prefer to either do it with inline styles or append a `<style>` tag with the appropriate CSS (kinda how Angular does it).
Are you working on this, otherwise i can lend a hand as well?

**Comment by bisubus** [comment]
Yes, that one required `setAttribute` (I wonder if it won't cause any issues, because `setAttributeNS` is usually recommended for SVG).
Not really a requirement but an option, it totally depends on parent element styling in this case, e.g. to fill Bootstrap column (adding `width: 100%` with option enabled seems to be pretty universal to me).
That's how I dealt with this.
bisubus/angular-svg-round-progressbar@c980d28998708e571ff52e7d39c53ababf334cbf

**Comment by crisbeto** [comment]
Looks mostly good, but there are a couple of things:
* Could you merge the latest changes into your PR?
* Looks like `viewBox` doesn't work on IE. I tried with `setAttributeNS` or just setting the property on the element, but it still doesn't work.

**Comment by bisubus** [comment]
Yes, I will merge and test it, PR it a couple of days later. Which IE has problems? I've checked it only in IE11.

**Comment by crisbeto** [comment]
I tested on IE11 as well. The element just doesn't scale.

**Comment by bisubus** [comment]
Sorry, I totally forgot about SVG scale bugs in IE, I don't remember if this one (there are several of them) affects either all SVGs or only inline. My use case had a placeholder in container that held its height, so it wasn't an issue for me.
The fix for this would be a trick like [this](http://plnkr.co/edit/H12mm6SKPmCPQbfEcEld?p=preview) (see `<div><svg ...></div>` part). I'm not sure if there are more elegant solutions.

**Comment by crisbeto** [comment]
Well its not too bad. Does it work if you change the viewBox dynamically?

**Comment by bisubus** [comment]
It should. And viewBox routine should be added to the watcher as well. Should we add div wrapper to the template then? Doing `display: inline` for div when `fitted` option is disabled should be fine (I think it has a better chance as a transparent container than `display: inline-block`).

**Comment by crisbeto** [comment]
Yeah I suppose so. I also think we should move the inline styles to a stylesheet to reduce the specificity, but I can do that afterwards.

**Comment by bisubus** [comment]
Ok, I will make some field tests and come up with something.

**Comment by amergin** [comment]
Any news on this? I would love `angular-svg-round-progressbar` to function in a similar manner that `angular-spinner` does. That is, place the directive instantiating element inside whatever container you wish, and the directive automagically centers the spinner horizontally and vertically. 

I'm having problems figuring how to center the circular progressbar in a similar way, in a situation where the container element dimensions can change.

**Comment by crisbeto** [comment]
Ops, I had forgotten about this issue. I'll take care of it when I have time, but until then you should be able to center the circle with CSS.

**Comment by bisubus** [comment]
I've tested the previous option (SVG with viewBox and `position: absolute`) inside `position: relative` container, most of the time it is acceptable but it tends to suffer occasionally from browser compatibility issues when being placed into complex responsive layout. I hope there is more universal solution.

**Comment by crisbeto** [comment]
The viewBox isn't necessary, when you're using the solution with `position:relative/absolute;`.

**Comment by crisbeto** [comment]
@bisubus and @amergin I've released this in [0.2.11](https://github.com/crisbeto/angular-svg-round-progressbar/releases/tag/0.2.11). Tested in the latest versions of all major browsers and its seems to work. Haven't had time to test in IE9, though.

**Comment by kbiedrzycki** [comment]
It's still something wrong here, the container has 100% width and height, but the svg inside (path) draws using wrong radius (not calculated dynamically, but still takes the value from radius parameter). Can you do something with that?

**Comment by crisbeto** [comment]
Thing is that when the `responsive` option is on, the SVG element gets stretched to fit the parent and doesn't take into account the radius any more, although the radius/stroke ratio is the same. I don't think there's a way around this.

**Comment by kbiedrzycki** [comment]
@crisbeto hm that's weird, cause when I tried demo page it looks okay there, the chart is responsive, but when I set same options on my page and try to run it, the svg circle size is bigger and it overflows from svg

**Comment by crisbeto** [comment]
I've only been testing with the demo page. It would be nice for some kind of minimal test scenario. 

As an aside: The demo page has `* { box-sizing: border-box; }`, maybe that could be the issue?

**Comment by kbiedrzycki** [comment]
I also have set the box-sizing to border-box, I've also tried to remove other styles and nothing helped.. Ill leave it for now (I've added listener for window innerWidth to change the radius for now), but I will get back to this and let you when I'll find the solution, thanks!

**Comment by crisbeto** [comment]
I'll close this for now, if anybody has issue with this just comment or open another issue.

**Comment by ahmdyml** [comment]
I'm having a similar issue with @kbiedrzycki . I set responsive true, and SVG element was scaling well, until we have to add Jquery to project. Then it started to overflow. We removed Jquery and it is fine.

**Comment by crisbeto** [comment]
Are you getting something like this @ahmdyml? I hadn't assumed adding jQuery would be an issue.
![screenshot_1](https://cloud.githubusercontent.com/assets/4450522/9658166/898abbf0-5247-11e5-87b7-5860382e12eb.png)

**Comment by crisbeto** [comment]
Looks like jQuery makes attributes lowercase which breaks the `viewBox` which is case-sensitive.

**Comment by crisbeto** [comment]
I've pushed [0.3.2](https://github.com/crisbeto/angular-svg-round-progressbar/releases/tag/0.3.2) @ahmdyml could you let me know if it works as expected?

**Comment by ahmdyml** [comment]
@crisbeto  Yes, it is. It scales well with Jquery now. Thanks.
