### ISSUE TITLE
error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

### ISSUE THREAD

**Issue by NexPlex** [crisbeto/angular-svg-round-progressbar#232]
Hi I'm getting this error with Angular 14

Error: node_modules/angular-svg-round-progressbar/round-progress/round-progress.component.d.ts:65:18 - error TS2707: Generic type 'ɵɵComponentDeclaration' requires between 7 and 8 type arguments.

65     static ɵcmp: i0.ɵɵComponentDeclaration<RoundProgressComponent, "round-progress", never, { "current": "current"; "max": "max"; "radius": "radius"; "animation": "animation"; "animationDelay": "animationDelay"; "duration": "du
ration"; "stroke": "stroke"; "color": "color"; "background": "background"; "responsive": "responsive"; "clockwise": "clockwise"; "semicircle": "semicircle"; "rounded": "rounded"; }, { "onRender": "onRender"; }, never, never, false, never>;

**Comment by crisbeto** [comment]
This usually happens if the required version of Angular of the progressbar library and your project's Angular version don't match. If you're on version 14 of Angular, you should be using version 9 of the progress bar.

**Comment by NexPlex** [comment]
I see. I uninstalled version 10 and installed version 9. It seems ok now. thanks
