### ISSUE TITLE
Only void and foreign elements can be self closed "round-progress"

### ISSUE THREAD

**Issue by Fahad11-dev** [crisbeto/angular-svg-round-progressbar#236]
Error: src/app/pages/dashboard/home/home.component.html:613:5 - error NG5002: Only void and foreign elements can be self closed "round-progress"

613     <round-progress
        ~~~~~~~~~~~~~~~

  src/app/pages/dashboard/home/home.component.ts:17:16
    17   templateUrl: './home.component.html',
                      ~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component HomeComponent.
    
    
    <p-dialog header="Header" [visible]="true" [style]="{width: '50vw'}" [draggable]="true">
    <round-progress
        [current]="current"
        [max]="max"
        [background]="background"
        [radius]="radius"
        [stroke]="stroke"
        [semicircle]="semicircle"
        [rounded]="rounded"
        [clockwise]="clockwise"
        [responsive]="responsive"
        [duration]="duration"
        [animation]="animation"
        [animationDelay]="animationDelay" />
</p-dialog>

**Comment by crisbeto** [comment]
Self-closing tags have been supported since Angular v16. You're likely on an older version.
