### ISSUE TITLE
ng-repeat

### ISSUE THREAD

**Issue by msnpr567** [crisbeto/angular-svg-round-progressbar#24]
Will it support ng-repeat?

**Comment by crisbeto** [comment]
I haven't really tried it, but it should work. Have you had any problems with it?

**Comment by crisbeto** [comment]
I'm assuming its solved, if you get any issues, you can re-open it.

**Comment by crisbeto** [comment]
I was playing around with it, and indeed there are issues when the directive is used with ng-repeat. Reopening.

**Comment by crisbeto** [comment]
Fixed in [0.2.9](https://github.com/crisbeto/angular-svg-round-progressbar/releases/tag/0.2.9).
