### ISSUE TITLE
How to inverse the semi circle progress bar

### ISSUE THREAD

**Issue by michari** [crisbeto/angular-svg-round-progressbar#26]
Can I get semi circle progress bar inverted with all its current functionality?

**Comment by crisbeto** [comment]
Inverted how exactly? Do you want it to go clockwise/counter-clockwise?

**Comment by michari** [comment]
something like this 
![inverted](https://cloud.githubusercontent.com/assets/2651180/8356120/94323d26-1b10-11e5-8a89-f9cd1c8ef325.png)

**Comment by crisbeto** [comment]
Ah, I haven't considered flipping it upside down. You can always flip it with CSS though:

```css
  transform: rotate(180deg);
```

**Comment by michari** [comment]
okay great let me try that thanks!
