### ISSUE TITLE
Error rendering round when current > max

### ISSUE THREAD

**Issue by ivangarrido** [crisbeto/angular-svg-round-progressbar#30]
I'm facing a problem rendering the progressbar when the value exceeds the max value defined in the div parameter.

I want to display percents, so my max value should be 100, but i could need to display a percent value higher than 100, in which case I would like to show the bar full filled and the value.

A quick fix for me would be to write a function that returns the highest value between 100 and the current value and set that as the max value.

In the attached image below:

- a) The problem I got: max value is 100, current is 146.
- b) I set 200 as max value to show that in that case it renders ok.

![percent](https://cloud.githubusercontent.com/assets/10050964/8530359/dbc2ab58-2420-11e5-9f60-60a0437c9941.png)

**Comment by crisbeto** [comment]
Yes, this limit was on purpose. It might make sense to have an option to disable it though.

**Comment by crisbeto** [comment]
Released [0.2.9](https://github.com/crisbeto/angular-svg-round-progressbar/releases/tag/0.2.9) with a fix for this.

**Comment by ivangarrido** [comment]
Nice, thank you for your work.
