### ISSUE TITLE
Basics

### ISSUE THREAD

**Issue by sherfull** [crisbeto/angular-svg-round-progressbar#32]
I know that i might seem stupid, but it doesn't work to me. First, at the beggining, in <head> section, i added "<script src="js/roundProgress.js"></script>", and later, where i want progressbar to be, i added "<div
round-progress
max="10"
current="5"
color="#45ccce"
bgcolor="#eaeaea"
radius="100"
stroke="20"
semi="true"
rounded="true"
clockwise="false"
iterations="50"
animation="easeInOutQuart"></div>"
What am i doing wrong?

**Comment by crisbeto** [comment]
Works for me, are you sure you have a valid `div` tag? Looks like you missed to open and close it. This should work:

```html
<div
  round-progress
  max="10"
  current="5"
  color="#45ccce"
  bgcolor="#eaeaea"
  radius="100"
  stroke="20"
  semi="true"
  rounded="true"
  clockwise="false"
  iterations="50"
  animation="easeInOutQuart"></div>
```

**Comment by sherfull** [comment]
I have no idea. Div isn't a problem, i checked it lieke thousand times. </div> was there, but i forgot to paste it. Do i need to add something else to the head section? Currently there is only <script src="roundProgress.min.js"></script>.

**Comment by crisbeto** [comment]
You also need Angular.js and you need to have `angular-svg-round-progress` defined as a dependency. You can look at the source of the demo to see an example: https://github.com/crisbeto/angular-svg-round-progressbar/blob/master/build/index.html

**Comment by sherfull** [comment]
![heh](https://cloud.githubusercontent.com/assets/13244662/8594076/d8db15be-263d-11e5-8b17-4447a4bcc0e7.png)
Is that all? Because it still doesn't work. I don't even know what i am doing wrong.

**Comment by crisbeto** [comment]
Ah, its because you have that `<div style='...` that is not valid HTML. In your case, the HTML should look like:

```html
<div
  round-progress
  max="10"
  current="5"
  color="#45ccce"
  bgcolor="#eaeaea"
  radius="100"
  stroke="20"
  semi="true"
  rounded="true"
  clockwise="false"
  iterations="50"
  animation="easeInOutQuart"
  style="width: 10px; height: 20px; background: black;"></div>
```

Also note that I'm writing every attribute on a newline because its a bit more readable, but it can be written as:

```
<div round-progress max="10" current="5" color="#45ccce" bgcolor="#eaeaea" radius="100" stroke="20" semi="true" rounded="true" clockwise="false" iterations="50" animation="easeInOutQuart" style="width: 10px; height: 20px; background: black;"></div>
```

**Comment by sherfull** [comment]
I added additional div just to look if the whole file works.

**Comment by crisbeto** [comment]
Do you get anything in your error console?

**Comment by sherfull** [comment]
ReferenceError: angular is not defined

**Comment by crisbeto** [comment]
This means that you haven't include angular.js, or that its included after the progressbar module.

**Comment by sherfull** [comment]
But you saw on screen that im including it.

**Comment by crisbeto** [comment]
You're including it after the round-progress, it should be before. Try switching the places of the 2 scripts.

**Comment by sherfull** [comment]
Hmm. Now there is not a single error, but it still doesn't show the progress-bar :P

**Comment by crisbeto** [comment]
Have you defined the `ng-app` attribute and have you defined an Angular module?

**Comment by sherfull** [comment]
oki, thank you :)

**Comment by sherfull** [comment]
But i have another question. Is it possible to make the progress-bar counting all the time, not just after loading the page? I mean, i open page and bar goes to for example 50/235, and then it adds 1 every second, til it goes to full 235/235

**Comment by crisbeto** [comment]
You'd need to implement that logic yourself in your controller or service. You can see something similar in "File upload" demo.
