### ISSUE TITLE
Progress bar displaying incorrectly in Chrome Version 44.0.2403.89 (64-bit)

### ISSUE THREAD

**Issue by mauricio-gamboa** [crisbeto/angular-svg-round-progressbar#33]
I am having this issue only in Chrome Version 44.0.2403.89 (64-bit). Is it known issue or a new bug? Thanks

![screen shot 2015-07-24 at 5 30 19 pm](https://cloud.githubusercontent.com/assets/934577/8886565/e34279e6-3229-11e5-9063-cbef509e9ef9.png)

**Comment by crisbeto** [comment]
Hmm this is ...strange. I tried the demo in 44.0.2403.107 stable and 46.0.2463.0 canary and it looked normal. Can you post a link or the settings that you're using?

**Comment by mauricio-gamboa** [comment]
Never mind, it works fine now, I don't know what happened that day. Thanks!
