### ISSUE TITLE
Timing

### ISSUE THREAD

**Issue by rogihee** [crisbeto/angular-svg-round-progressbar#36]
Hi Chris,

great control! I want to time the from-to so that for example 0-100 takes 1 second.

You have the iterations attribute, but how can you convert that to a particular time?

Thanks!

Rogier

**Comment by crisbeto** [comment]
Hmm that's a good question, however its not possible at the moment. Its a good idea for a feature though.
I'm not quite sure how the math is supposed to work out, because I didn't write the easing functions and none of them take arguments for the duration of the animation.

**Comment by rogihee** [comment]
ok, you should be fine once you know the framerate. Duration = nriterations / framerate, right?

Been digging a little and you are using requestAnimationFrame, and then the browser is in control of the framerate.

If you would wrap that in a timeout you can control the framerate and always set it to 60, so nriterations / 60 = duration in seconds:
http://stackoverflow.com/questions/19000109/javascript-cant-adjust-framerate-requestanimationframe

Is that an idea?

**Comment by crisbeto** [comment]
I don't think reverting to using `setTimeout` is a good idea since the whole point of `requestAnimationFrame` is to do away with timer-based animations. After a bit of fiddling I managed to get the animations to execute in a certain amount of ms, although it didn't quite work out with the easing. 
![a](https://cloud.githubusercontent.com/assets/4450522/9293898/d95ad878-443b-11e5-8eae-fb246e83960a.gif)

**Comment by rogihee** [comment]
Thanks! That would even be great for my use case, the timing is more important than the easing, although it would make it nicer.
The problem with rAF is that it's based on the screen refresh rate, so typically 60Hz, but not guaranteed... 

http://creativejs.com/resources/requestanimationframe/
The author claims it will have same performance as rAF but throttled...

**Comment by crisbeto** [comment]
Turns out I didn't read the docs for the easing functions, they allow for time-based easing. Working on releasing it.

**Comment by crisbeto** [comment]
Released [0.3.0](https://github.com/crisbeto/angular-svg-round-progressbar/releases/tag/0.3.0) that replaces the `iterations` with a `duration`, thanks for the idea! 
Closing this issue, if there's anything wrong, comment or open a new one.
