### ISSUE TITLE
can we implement progress bar with one side butt and other side rounded?

### ISSUE THREAD

**Issue by phani9046** [crisbeto/angular-svg-round-progressbar#37]
can the progress bar be updated with one side butt and other side rounded?

**Comment by crisbeto** [comment]
It can't, because it uses the `stroke-linecap` property that doesn't allow much flexibility. Using a mark might work, though. Note that you'd need to override the default template for it to work.
Info on markers: http://www.w3.org/TR/SVG/painting.html#Markers

**Comment by crisbeto** [comment]
I've posted an example of how to achieve this over in https://github.com/crisbeto/angular-svg-round-progressbar/issues/41. I'll close this issue for now, but feel free to comment or re-open it if there are any issues.
