### ISSUE TITLE
Progress is not centred exactly and in safari its way off

### ISSUE THREAD

**Issue by santbob** [crisbeto/angular-svg-round-progressbar#40]
thanks for this wonderful module, but it not exactly centred vertically. in safari it completely off.

Visiting https://crisbeto.github.io/angular-svg-round-progressbar/ in safari shows it.

In Chrome and Firefox, i see that the styles get assigned are 

```
    top: 50%;
    bottom: 50%;
    left: 50%;
    transform: translateY(-50%) translateX(-50%);
    font-size: 21px;
```
setting both top and bottom to 50% leaves the text to be of zero height, may be the css needs to be reconsidered

**Comment by crisbeto** [comment]
Hey, thanks for reporting this. It was actually a case of me forgetting the vendor prefixes on the `transform`. Its fixed now.

**Comment by santbob** [comment]
@crisbeto thanks for fixing it super fast, can you push a bower version as well.

**Comment by crisbeto** [comment]
This is a change only in the demo, I don't think it needs a release.
