### ISSUE TITLE
Animation not working properly in Android Ionic framework

### ISSUE THREAD

**Issue by ajaybeniwal** [crisbeto/angular-svg-round-progressbar#42]
I have added the library to my hybrid app project in Ionic framework to show user rating but it works some time and does not work many times 

![screenshot_2015-09-30-07-31-45 1](https://cloud.githubusercontent.com/assets/658004/10185222/502d1246-6763-11e5-8a24-5a7a1b535da2.png)

**Comment by crisbeto** [comment]
Could you you upload the screenshot and the options that you're using to Github? I can't view the link on Slack.

**Comment by ajaybeniwal** [comment]
I updated the screenshot of it

**Comment by crisbeto** [comment]
This seems like an issue when resizing, although it doesn't look like you're changing the size dynamically. 
Do you happen to have access to the console to see if any errors are being thrown? 
Also do you know what version of the Android WebView you're using?
And a bonus question: Which version of the progressbar module are you using? Has this happened on older versions? (I've changed some of the `$watch`-es in the last 0.3.3 and that might be causing some values not to re-render)

**Comment by ajaybeniwal** [comment]
This is installed on android phone so it is not being resized by any means
using webkit version 537.36 running on android 5.0
There are no console errors in the log.
I am using version 0.3.2 right now.

**Comment by crisbeto** [comment]
Hmm ok I'll try to look into it when I get an Android emulator to work. Until then you can try to update ot 0.3.3 or 0.3.4 (they're the same)

**Comment by crisbeto** [comment]
Running the demo page in the built-in Android browser on 5.0.2 worked fine. Do you have any CSS that modifies `svg` or `path`?

**Comment by ajaybeniwal** [comment]
No I do not modified the CSS path

**Comment by crisbeto** [comment]
Then this might be tricky to debug without running the app itself.

**Comment by ajaybeniwal** [comment]
Okay i have added the new version of plugin so lets see if it works or not

**Comment by crisbeto** [comment]
Did you have any luck with the newer version?

**Comment by ajayequinix** [comment]
It works fine with latest version
