### ISSUE TITLE
Non angular dependent version

### ISSUE THREAD

**Issue by JCMais** [crisbeto/angular-svg-round-progressbar#44]
Any plans to a version that is not dependent on angular?

**Comment by crisbeto** [comment]
Actually I have quite recently. This weekend I was fiddling with Babel and considering porting it to ES6 but it would introduce a dependency either on Require.js or Browserify or something similar. I ended up deciding to do it in ES5 and I've made a little bit of progress. I don't have a timeframe on when it would be ready though.

**Comment by JCMais** [comment]
Good to know, thanks for info.

**Comment by JCMais** [comment]
@crisbeto Hi, did yout got it any further?

**Comment by crisbeto** [comment]
Not really, I've been pretty busy with some other projects and I just haven't had the time to look into it further.

**Comment by teacoat** [comment]
@JCMais there are tons of plugins like this for other languages already
