### ISSUE TITLE
Angular bracket interpretation not working with "max" or "current" parameters

### ISSUE THREAD

**Issue by cnash6** [crisbeto/angular-svg-round-progressbar#47]
I am attempting to use your progress bar in a custom directive with which I can pass in values easily to many instances of progress bars.  However, using angular's `{{variable}}` notation is not working as far as I can tell.  Here's what I'm doing: 

```
<div round-progress
       max="{{thing}}"
       current="50"
       color="#F96302"
       radius="50"
       stroke="15"
       semi="false"
       rounded="false"
       clockwise="true"
       responsive="false"
       duration="1200"
       animation="easeInOutQuart">
</div>
```

And I get the following error:

```
Error: [$parse:syntax] Syntax Error: Token '{' invalid key at column 2 of the expression [{{thing}}] starting at [{thing}}].
http://errors.angularjs.org/1.4.7/$parse/syntax?p0=%7B&p1=invalid%20key&p2=2&p3=%7B%7Bthing%7D%7D&p4=%7Bthing%7D%7D
```

Interestingly, I do not get this error when I attempt this syntax with the `radius` parameter, and passing in `{{thing}}` as the value there does not result in any errors.

`thing` is defined on my controller as `$scope.thing = 200`

Any chance you can help me figure this out?  I love your package and would love to keep using it!

**Comment by crisbeto** [comment]
It's not supposed to be working with the bracket notation. For max and current you can pass in the value directly. In your case it should be `max="thing"`.

**Comment by cnash6** [comment]
Well now I feel silly for not trying that in the first place.  Thanks! It works now!

**Comment by crisbeto** [comment]
You're welcome.
