### ISSUE TITLE
Responsive error

### ISSUE THREAD

**Issue by Duovili** [crisbeto/angular-svg-round-progressbar#48]
I am trying to run this with angular material in one of the flex containers but it doesnt seem to work. Have you have this issue as well?

**Comment by crisbeto** [comment]
Sorry, I'm not using Angular material. Do you have somewhere I can check this out? Maybe a fiddle or some other live example.

**Comment by Duovili** [comment]
I think it might be the new release. I had to hard code responsive true into the library then it worked. otherwise it wasnt picking up my value set in the directive. So it has nothing to do with angular material.

**Comment by crisbeto** [comment]
The new release had nothing to do with `responsive`, though, it only added a fallback if the document had a `<base>` tag. Passing responsive works fine in the demo. Can you share the HTML that you're using?

**Comment by Duovili** [comment]
<div class="small-graphs">
                <div class="graph">
                    <div
                        round-progress
                        max="data.stats.totalBrandUsers"
                        current="data.stats.gender.male"
                        color="#ff8a80"
                        bgcolor="#b71c1c"
                        stroke="10"
                        semi="false"
                        rounded="false"
                        clockwise="true"
                        responsive="true"
                        duration="800"
                        animation="easeInOutQuart"></div>
                    <span class="percentage">{{(math.floor(data.stats.gender.male / data.stats.totalBrandUsers * 100))|| 0}}</span>
                    <h4>Men</h4>
                </div>

you can see that I am running it as the usual specs; but responsive only changed when I set in in the library. All the other options work except responsive. I am not concerned because I made it work. But just an FYI

**Comment by crisbeto** [comment]
Of course, thanks for reporting it. I think you got the wrong snippet, though.

**Comment by Duovili** [comment]
I took that off this repository; what did I do wrong? the other HTML is just to illustrate the containers it is in.

**Comment by crisbeto** [comment]
This is the only HTML that I'm seeing:

```html
<span class="percentage">{{(math.floor(data.stats.gender.male / data.stats.totalBrandUsers * 100))|| 0}}</span>
                <h4>Men</h4>
            </div>
```

**Comment by crisbeto** [comment]
Ah I'm sorry, Github just wasn't rendering the whole thing. When I clicked "Edit" I could see the full snippet. I can't see anything wrong, my best guess is that a digest wasn't triggered when you were setting `responsive` as a variable. I'll close this for now, but feel free to comment or re-open it if there's still an issue.
