### ISSUE TITLE
CSS issue

### ISSUE THREAD

**Issue by comapedrosa** [crisbeto/angular-svg-round-progressbar#49]
I have looked the documentation and I can't find it, how do I put the progress in the middle of the round progress bar as it is on the demo?
![screen shot 2015-11-09 at 17 21 17](https://cloud.githubusercontent.com/assets/3918797/11039092/50000446-8706-11e5-8098-977b8d737c44.png)

**Comment by crisbeto** [comment]
If you're refering to the text, it's not included in the directive. You can take a look at the demo to see how it's being added with CSS. [This is the base style](https://github.com/crisbeto/angular-svg-round-progressbar/blob/master/build/index.html#L28) and [the rest of the styles](https://github.com/crisbeto/angular-svg-round-progressbar/blob/master/build/index.html#L313) are being added with JS so the text can react to changes in the progressbar size, but if you know that your size won't change, you can put everything in your CSS.

**Comment by comapedrosa** [comment]
Sorry guys, I found it on a closed issue, should have looked better before posting. You have the answer here https://github.com/crisbeto/angular-svg-round-progressbar/issues/34. Great project! Thank you very much for this awesome work!
