### ISSUE TITLE
Error: easingAnimation is not a function. (In 'easingAnimation(currentTime, start, changeInValue, duration)', 'easingAnimation' is undefined)

### ISSUE THREAD

**Issue by arist1213** [crisbeto/angular-svg-round-progressbar#50]
I used ionic framework (side-menu), when i toggle the side menu bar, it caused this 
Error: easingAnimation is not a function. (In 'easingAnimation(currentTime, start, changeInValue, duration)', 'easingAnimation' is undefined)

Is it the animation conflict with ionic side menu animation ?

Your system information:

Cordova CLI: 5.0.0
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 1.1.0
Ionic CLI Version: 1.6.4
Ionic App Lib Version: 0.3.8
ios-deploy version: Not installed
ios-sim version: 3.1.1
OS: Mac OS X Yosemite
Node Version: v0.12.2
Xcode version: Xcode 7.1 Build version 7B91b

**Comment by crisbeto** [comment]
I doubt it's conflicting with Ionic. What value have you set as `animation` on the element or in the `roundProgressConfig`?

**Comment by arist1213** [comment]
easeOutCubic

**Comment by crisbeto** [comment]
Works fine when trying it in the demo. My best guess is if you have a typo in the name, or if you specified it with some space before/after `roundProgressConfig.animation = 'easeOutCubic ';`. 

We can try to debug it by using the [unminified version](https://github.com/crisbeto/angular-svg-round-progressbar/blob/master/build/roundProgress.js) and adding `console.log(options.animation);` [at line 427](https://github.com/crisbeto/angular-svg-round-progressbar/blob/master/build/roundProgress.js#L427).

**Comment by arist1213** [comment]
![image](https://cloud.githubusercontent.com/assets/1732076/11168074/6958f11a-8bba-11e5-9e64-a413aa6af26e.png)

**Comment by arist1213** [comment]
This is not happened every time, maybe is mine code generated. I don't know.
I open a side menu and get into a special sub menu,  when I close it, error appears first time. After that is ok. It's weird.

**Comment by crisbeto** [comment]
It's fine, that's what GitHub is for. I still find it kinda strange, the log that you posted looks good.

I just noticed that the same error happens with something like `<div round-progress animation=""></div>` or `<div round-progress animation></div>`. Can you share the HTML that you're using to define your progressbar?

**Comment by crisbeto** [comment]
It's been a while since this was opened and I still haven't been able to reproduce it.
