### ISSUE TITLE
suggestion: add animation-delay property

### ISSUE THREAD

**Issue by paulocheque** [crisbeto/angular-svg-round-progressbar#51]
Example: animation-delay: 50ms

This could be useful to interact with other page animations.

By the way, great lib!

**Comment by crisbeto** [comment]
Thanks for the suggestion, I'll take a look when I have time.

**Comment by crisbeto** [comment]
Sorry that this took a while but I've been busy these last couple of months. The `animationDelay` property is added in the [0.3.9 release](https://github.com/crisbeto/angular-svg-round-progressbar/releases/tag/0.3.9).
