### ISSUE TITLE
starting progress halfway through

### ISSUE THREAD

**Issue by Slavrix** [crisbeto/angular-svg-round-progressbar#52]
If i set the max to 900 and the current to 600, 
Instead of seeing the circle 1 3rd complete already 
it looks like the max sets itself to be the current then it starts from there.

Is this working as intended?

**Comment by crisbeto** [comment]
Are you referring to it starting to animate from 0 instead of just starting from 600?

**Comment by Slavrix** [comment]
so max would be 900 and it would start from current being 600

**Comment by crisbeto** [comment]
I'm not quite sure what you're referring to. I ran the demo page with a max of 900 and a current of 600 and it works as intended. The idea is that the first animation should start from 0.

**Comment by Slavrix** [comment]
So to do what i wanted i ended up just starting the countdown with both the value and max value the same (so with this example both 900)
then i set vale to 600 straight away so it starts 1/3rd completed.
