### ISSUE TITLE
specify custom width for svg circle

### ISSUE THREAD

**Issue by upender15** [crisbeto/angular-svg-round-progressbar#56]
I'm using this as a small dashboard which shows 6 svg circles with different values. I tried to specify custom width to make circles small but I couldn't. Any help please? 
something like this in the image:

![f562ec138713efd00c7d3727a1ff4570](https://cloud.githubusercontent.com/assets/9474837/12489448/44436b7c-c025-11e5-8c2a-709fa852996a.jpg)

**Comment by crisbeto** [comment]
I'm not sure the size of what you're referring to. Do you want to specify the size of the whole progressbar or just the background?

**Comment by upender15** [comment]
I want to specify svg width of whole progress bar circle.
Like this:
![progressbar](https://cloud.githubusercontent.com/assets/9474837/12489969/f67ba8f2-c027-11e5-93ff-a83c9bfd6f63.PNG)

**Comment by crisbeto** [comment]
You need to use the `radius` option. The width of the circle (the diameter) is equal to 2x whatever is specified as the `radius`, e.g. if you want a circle of width 100, you need to set the `radius` to 50.

**Comment by upender15** [comment]
yeah this works. Thanks...!!!
