### ISSUE TITLE
Set start point for rendering.

### ISSUE THREAD

**Issue by wickY26** [crisbeto/angular-svg-round-progressbar#59]
First of all great directive.

I am using your directive to show how many percentage of some duration completed (some kind of task duration). It is working like a charm. Now I want to design a scheduler by using your directive.In my mind it will be like a clock and user can set start time for task and set duration as well and I want only selected part to be colored. Right now there is no start point options so my question is there any workaround you can suggest or am I missing something?

![roundbar](https://cloud.githubusercontent.com/assets/5011438/13219992/12c7f566-d97c-11e5-984a-ac090c79ca3a.png)

an example view of how I want to do is something like that. In that example I indicate task will start at 4 and finish at 8...

**Comment by crisbeto** [comment]
I'm not quite sure I get your idea. If you want the progress to start from a particular point that's not the top middle, you can rotate the progressbar with CSS.
