### ISSUE TITLE
using the progressbar within ng-repeat

### ISSUE THREAD

**Issue by nmoore2** [crisbeto/angular-svg-round-progressbar#60]
This is also more of a question than an issue.

I'm using the progressbar within an ng-repeat. How can I animate each of the progress bars separately? I'm currently using a function like the one seen here to update the 'current' attribute https://fiddle.jshell.net/c1k13uaa/3/

But by using this method, all of the progress bars share the same 'current' value, and are all animating at the same time.

**Comment by crisbeto** [comment]
You could make it an array of values (or objects if you want to specify more options) and increment them individually. [Here's a fork of your fiddle that shows a simple example](https://fiddle.jshell.net/37rdw8p0/1/).

**Comment by nmoore2** [comment]
Thank you!! This worked beautifully.
