### ISSUE TITLE
text in the center...

### ISSUE THREAD

**Issue by clembou590** [crisbeto/angular-svg-round-progressbar#63]
Hello.
Everything is in the title...:
how to add text in the center? (as in your exemple:http://crisbeto.github.io/angular-svg-round-progressbar/)
thanks for the work.

**Comment by crisbeto** [comment]
You can refer to [the demo's source code](https://github.com/crisbeto/angular-svg-round-progressbar/blob/master/build/index.html) or https://github.com/crisbeto/angular-svg-round-progressbar/issues/55 or https://github.com/crisbeto/angular-svg-round-progressbar/issues/27 which have dealt with this.
