### ISSUE TITLE
From last change from angular-svg-round-progress to angular-svg-round-progressbar

### ISSUE THREAD

**Issue by GoriX** [crisbeto/angular-svg-round-progressbar#64]
Hi, 

I have a problem animation in circle round progress from last update, only in mobile device with IOS in Safari and Chrome, in desktop pc works fine... :(

Effect animation with delay time directly not appear only I can see background color but not main color with progress...

Can you help me?

Best regards.

**Comment by crisbeto** [comment]
What version of iOS are you running? I assume that it might be because of the animation timing stuff.

**Comment by GoriX** [comment]
I have Iphone 5 with IOS 7.1.2 , thing is that in previous weeks progress bar worked fine always in all mobiles but from last changes not....

Thanks for your fast reply.

**Comment by crisbeto** [comment]
Hmm ok that's pretty old, let me see if I can reproduce it.

**Comment by GoriX** [comment]
OK, I tested with your test page too and it doesn't works, maybe you can review last changes in your code for css compatibility or other things....

**Comment by crisbeto** [comment]
My bet is on the "Started using performance.now for the animation timing, if the browser supports it.", it doesn't have the best browser support, although I tried to polyfill it.

**Comment by GoriX** [comment]
I used your progress bar one month ago just because it worked very fine in mobile devices, your demo is in 800 ms, I have 2500 ms and worked fine.

**Comment by crisbeto** [comment]
I can't reproduce this with any of the devices and VMs I have lying around. Would you be able to try out a fix by replacing the file manually?

**Comment by crisbeto** [comment]
Well I've released 0.4.2 that should solve, what I think, is the issue. Let me know if it works.

**Comment by GoriX** [comment]
Yesss!! Works fine with 0.4.2.... super, thanks a lot....
![img_6458](https://cloud.githubusercontent.com/assets/15001864/14159910/2b9c0198-f6d9-11e5-994f-3b585442a8f2.PNG)
