### ISSUE TITLE
Unable to use it in angular

### ISSUE THREAD

**Issue by kkorada** [crisbeto/angular-svg-round-progressbar#66]
getting error

**TypeError: e.$watchGroup is not a function
    at b.isSupported.angular.extend.link (http://crisbeto.github.io/angular-svg-round-progressbar/roundProgress.min.js:2:7730)**

**Comment by crisbeto** [comment]
My guess is that your Angular version might not have the `$watchGroup` method. I believe it was introduced in 1.2 or 1.3.

**Comment by kkorada** [comment]
yes it didn't have `$watchGroup`, i am using older version of angular, thank you.
