### ISSUE TITLE
Text inside progressbar

### ISSUE THREAD

**Issue by vithanidarpan** [crisbeto/angular-svg-round-progressbar#67]
I have implemented your sample demo.
During implementation I got one problem, text inside circle is not displayed.
Also I need to know how to change default text of progress bar.
For example I want to display any custom text instead of that "27/50" (any value), how can I do that.
Thanks in advance.

**Comment by crisbeto** [comment]
The component does not support text by default. This is on purpose. You can refer to #27, #55 or #63 for more info on how it's done in the demo and how you can implement it in your own project.
