### ISSUE TITLE
Binding

### ISSUE THREAD

**Issue by digirew** [crisbeto/angular-svg-round-progressbar#69]
I want to be able to change the values of the progress bar from within the controller, but the values aren't updated or even parsed - I don't know if this is some binding issue or what...

```
<div round-progress
                        max="{{project.timer.max}}"
                        current="{{project.timer.current}}"
                        bgcolor="{{project.timer.transparent}}"
                        radius="{{ project.timer.radius*1.5 }}"
                        stroke="{{ project.timer.stroke }}"
                        offset="inherit"></div>
```

I'm using vm instead of $scope - is this a possible source of issue?

**Comment by crisbeto** [comment]
This isn't a whole lot to go on. Are you sure you're triggering a digest when the values change? Try wrapping your code in a `$scope.$apply`.

**Comment by digirew** [comment]
Sorry - I have a model defined as something like this (all the values are there)
```
            vm.projects[index].name="project a";
            vm.projects[index].timer.current =        27;
            vm.projects[index].timer.max =            50;
            vm.projects[index].timer.offset =         0;
            vm.projects[index].timer.timerCurrent =   0;
            vm.projects[index].timer.uploadCurrent =  0;
            ...
```
then i have a ng-repeat ="project in projects"

all the other values in the ng-repeat are filled and used (like name), but not for this directive...

**Comment by crisbeto** [comment]
Sorry, but this still isn't enough to go on. The demo uses the same types of bindings and I just tried it with a ngRepeat and it worked fine. Can you try to isolate it into a fiddle/codepen?
