### ISSUE TITLE
Nested progress bar Style?

### ISSUE THREAD

**Issue by bgadiel** [crisbeto/angular-svg-round-progressbar#70]
Hi,
How can I control the nested progress bar style?
I implemented your clock example code and the nested item is is not centered correctly.
![screenshot at apr 26 12-32-14](https://cloud.githubusercontent.com/assets/10960597/14813626/3b20bad2-0bab-11e6-8f9f-4f9fa33cd109.png)

**Comment by crisbeto** [comment]
Are you sure there's no other CSS on the page messing with it? Also what browser are you testing on?

**Comment by bgadiel** [comment]
I use Chrome, and yes, there is a lot of CSS going around.
What parameter controls the center value of the bars?

**Comment by crisbeto** [comment]
Well there's quite a lot that could influence it, like `position`, `transform`, `top/bottom/left/right`, `transform-origin`, as well as modifying the `viewBox` on any of the parent SVGs.

**Comment by bgadiel** [comment]
issue solved.
problem was I used different 'radius' values for inner and external circles.
