### ISSUE TITLE
Is it possible to add a feature which shows different colors in the circle?

### ISSUE THREAD

**Issue by rajeshwarpatlolla** [crisbeto/angular-svg-round-progressbar#74]
Something like the below image.

![nat partouche - messages](https://cloud.githubusercontent.com/assets/9896335/15501551/b59abd86-21cb-11e6-8184-f2121bf40d8d.png)

It would be really a great feature for this plugin. I am in need of this feature. I tried to find a few plugins, but i didn't find one. I was using your plugin earlier, so thought to suggest you this feature. If you can add this feature, that would be really helpful.

**Comment by crisbeto** [comment]
It would be tricky to make it exactly as your screenshot, but you might have some luck with using a gradient as the fill color. Check the demo and select the "Gradient" checkbox.

**Comment by rajeshwarpatlolla** [comment]
Yeah, it would be tricky, but it adds a great feature to this plugin.

**Comment by rajeshwarpatlolla** [comment]
Yes, but if you can add this feature, it would be great plus for this plugin.

**Comment by crisbeto** [comment]
Closing the issue since I don't intend on adding this.
