### ISSUE TITLE
Masking the progress animation? 

### ISSUE THREAD

**Issue by partialdata** [crisbeto/angular-svg-round-progressbar#76]
Would it be difficult to mask the progress animation? I was trying some different things out but i couldn't get the image on top of the progress bar.

**Comment by crisbeto** [comment]
Not sure what you mean exactly, but if you're trying to put an image inside the circle, you can check #34.

**Comment by partialdata** [comment]
something like this. You see the image of thoe circles would mask the the progress animation 

![mask](https://cloud.githubusercontent.com/assets/6014478/15806419/e6d02c8a-2b10-11e6-97bd-f0f5368353c7.png)

**Comment by crisbeto** [comment]
It's not supported out-of-the-box, but I managed to get [the answer from here to work.](http://stackoverflow.com/questions/16988156/is-it-possible-to-use-a-background-image-on-the-stroke-of-an-svg-element). Just throw this somewhere into your page:

```html
<svg>
    <defs>
        <pattern id="p1" patternUnits="userSpaceOnUse" width="32" height="32">
            <image xlink:href="http://phrogz.net/tmp/alphaball-small.png" width="32" height="32" />
        </pattern>
    </defs>
</svg>
```

Then specify the stroke on your progressbar:

```html
<round-progress max="max" current="current" color="url(#p1)"></round-progress>
```

**Comment by partialdata** [comment]
Thank you for looking into this but instead of a image inside mask the outside like this. 
![bb0ccc6c-2b14-11e6-8302-c415c8409619](https://cloud.githubusercontent.com/assets/6014478/15806794/c9a01284-2b19-11e6-9ec4-2ed09a5c81c5.gif)

**Comment by crisbeto** [comment]
You might get different results with a bigger image and playing around with the SVG options.

**Comment by partialdata** [comment]
Thanks again for this cool progress bar and letting us use it! Ill play around with svg options.
