### ISSUE TITLE
infinite transition 

### ISSUE THREAD

**Issue by partialdata** [crisbeto/angular-svg-round-progressbar#77]
the clock example on the demo page the seconds increment with  a ticking motion... is there away to do continuous transition like the top clock in the image below?
![second-hand](https://cloud.githubusercontent.com/assets/6014478/15897501/adc51190-2d62-11e6-83c3-3edde00589e4.gif)

**Comment by crisbeto** [comment]
You can transition from 0 to 59 and set the transition duration to 1 minute.

**Comment by partialdata** [comment]
AH! Thank you I totally see now duh!

**Comment by partialdata** [comment]
I have tried to incorporate the duration but in my countdown timer example here http://codepen.io/partialdata/pen/oLbMpm  I am not sure how to do so. Any tips?

**Comment by crisbeto** [comment]
That's because you're still decrementing the `$scope.timer` by 1 each second. You're supposed to start from 10 and set it to 0, in addition to setting the `duration` to 10sec (10000ms).

**Comment by partialdata** [comment]
I searched around here and found that you mentioned "you can programmatically determine the current value" [#45](https://github.com/crisbeto/angular-svg-round-progressbar/issues/45#issuecomment-149799920)   But i am not able to get this to work... I need to keep track of the current or max values to know when the timer has completed.

**Comment by crisbeto** [comment]
The answer on #45 doesn't really keep track of the current value, it tells the progressbar what the current value is. If you want to know what the value is, you can pass a `on-render` callback:

```html
<round-progress on-render="getCurrent"></round-progress>
```

```js
$scope.getCurrent = function(value){
    console.log(value);  
};
```

**Comment by partialdata** [comment]
Dude thank you for your help! Really appreciate it!

**Comment by ChrisFuck** [comment]
@crisbeto 
hey bro ,I use angular 4 .
And I'm trying to set [onRender] property ,I got this error as the following:
"Binding to event property 'onRender' is disallowed for security reasons, please use (Render)=",
when I use the (Render)= ,I got another error said "Can't bind to 'Render' since it isn't a known property of 'round-progress'."

can you give me a hand, thx

**Comment by ChrisFuck** [comment]
[
![wechatimg1](https://cloud.githubusercontent.com/assets/10722776/25934537/124acb94-3651-11e7-958d-6321d39909ff.jpeg)
](url)

@crisbeto this is my code

**Comment by ChrisFuck** [comment]
![wechatimg2](https://cloud.githubusercontent.com/assets/10722776/25934568/4ac98460-3651-11e7-8dd2-0d3c7fd9db1c.jpeg)


@crisbeto  this is my code

**Comment by crisbeto** [comment]
You're supposed to use `(onRender)="getCurrent($event)"`.
