### ISSUE TITLE
ng-repeat and $interval

### ISSUE THREAD

**Issue by jaiswalmanish** [crisbeto/angular-svg-round-progressbar#79]
it seems the progress is not smooth when used with ng-repeat to have multiple progress and data increment is happening on regular interval.

<div ng-repeat="db in test">
            <div class="progress ng-cloak" ng-style="getStyle()">{{ current }}/{{ max }}</div>
            <div
                round-progress
                max="max"
                current="current"
                color="{{ getColor() }}"
                bgcolor="{{ bgColor }}"
                radius="{{ radius }}"
                semi="isSemi"
                rounded="rounded"
                stroke="{{ stroke }}"
                clockwise="clockwise"
                responsive="responsive"
                duration="{{ duration }}"
                animation="{{ currentAnimation }}"
                offset="{{ offset }}"
                animation-delay="{{ animationDelay }}">
                <svg>
                    <linearGradient id="gradient" x1="0" x2="0" y1="0" y2="1">
                        <stop offset="5%"  stop-color="green"/>
                        <stop offset="95%" stop-color="gold"/>
                    </linearGradient>
                </svg>
            </div>
        </div>
</div>

The value of current is getting increased by 1 at regular interval using $interval

**Comment by crisbeto** [comment]
Not sure what you mean, here's the example from the demo with ng-repeat:
![s](https://cloud.githubusercontent.com/assets/4450522/16141488/78ac432e-345c-11e6-8ca3-e7a9050ee527.gif)

**Comment by jaiswalmanish** [comment]
I have created a plunker for your reference-
http://plnkr.co/edit/iCkZqsB8PWH2zdZG1a1H?p=preview

**Comment by crisbeto** [comment]
The animation is resetting in your case because you overwrite the `$scope.numbers` on each interval, which causes the circle to be re-rendered. You should initialise the `$scope.numbers` on load and then only increment their `val`. [Here's a fork of your example that works.](http://plnkr.co/edit/qbfoUi6QlkAl9xiXnC0U?p=preview)
