### ISSUE TITLE
Completion callback

### ISSUE THREAD

**Issue by RyanWarner** [crisbeto/angular-svg-round-progressbar#80]
Thank you so much for this awesome module!

I would find it useful to have an attribute such as `on-complete` where I could specify a function to be called when the animation is done. Currently, I'm doing this with `on-render` and checking the current progress, but this feels wasteful.

Thoughts?

**Comment by crisbeto** [comment]
I get where you're coming from, but I decided to stick with one callback on purpose. Adding more feels like opening Pandor's box, where the module would have to be bloated with all kinds of callbacks (onStart, onEnd, onInit, onDestroy etc.).

**Comment by RyanWarner** [comment]
Cool, thanks for the thoughtful response. I see your point of view and will continue using `on-render` to check if it's complete.
