### ISSUE TITLE
Minimize watcher count

### ISSUE THREAD

**Issue by Ivshti** [crisbeto/angular-svg-round-progressbar#83]
I've been trying to optimize an angular (1) application, and I found out that every instance of round-progress is additional watchers for `max`, `color`, `bgcolor`, `radius`, `stroke` and `responsive`. Is it possible to use one-time binding for those?

**Comment by Ivshti** [comment]
Actually, even the properties that don't get set are watched

**Comment by crisbeto** [comment]
You can set a one-time binding in your own templates, just prefix the data binding with `::`. Otherwise excluding properties that aren't set from the `$watchGroup` makes sense.

**Comment by Ivshti** [comment]
afaik the watch group includes a fixed list of properties - how about filtering to only the ones which are set by the user?

also, I tried doing things like: max="::100", didn't work

**Comment by crisbeto** [comment]
By using one-time bindings, the watchGroup will still watch for changes, it just won't fire as often. I'll add filtering only for the specified properties when I get some more time.

**Comment by Ivshti** [comment]
I understand that, but can you give specific examples of how one-time binding works with round-progressbar?

I tried:
``max="::100" radius="::2.5"`` for starters, did not work at all (as if I didn't passed the props)

Angular 1.5.7

**Comment by crisbeto** [comment]
`max="100" radius="2.5"` Won't fire watchers at all since it doesn't have a data binding. The cases where it would are something like `max="{{ max }}"` in which case you can do `max="{{ ::max }}"` to turn it into a one-time binding.

**Comment by Ivshti** [comment]
Got it. I am confused by the fact that the watchers *exist*, I don't know when they're fired. Let me illustrate:
![screen shot 2016-07-06 at 19 35 37](https://cloud.githubusercontent.com/assets/1247629/16626272/da42d46e-43b0-11e6-9098-6033ac686841.png)

**Comment by crisbeto** [comment]
Yes, the way it works is that it passes an array of all the properties to `$watchGroup`, which then calls `$watch` on each of them behind the scenes. The difference between doing this and individual watches is that they all fire the same callback when any one of them changes.

**Comment by Ivshti** [comment]
Since this is a relatively vital issue for us - this directive adds around ~1000 watchers to our application - I implemented a (ugly) solution 

```
            if (scope.noListen) { 
                Object.keys(options).forEach(function(k) {
                    if (scope[k]) options[k] = scope[k]
                });
                renderState(scope.current, scope.current, true);
                renderCircle();
                return;
            }
```

after defining `renderState` (and ofc adding `"noListen: '@'"`)

Please think of a more elegant way to do this, and I'd PR

**Comment by crisbeto** [comment]
Done in [0.4.6](https://github.com/crisbeto/angular-svg-round-progressbar/releases/tag/0.4.6). Note that if you specified something like `max="100"`, it will still be watched, even though it doesn't have a data binding.
