### ISSUE TITLE
Conflict with Google Maps?

### ISSUE THREAD

**Issue by marcgetqd** [crisbeto/angular-svg-round-progressbar#85]
When I include the directive I get an error 

`Controller 'googleMap', required by directive 'circle', can't be found!`

https://docs.angularjs.org/error/$compile/ctreq?p0=googleMap&p1=circle

**Comment by crisbeto** [comment]
Hmm that's weird. The progressbar uses SVG's `circle` element to draw the background, but that's about it. You might have some other module on your page that's defining a `circle` directive.

**Comment by marcgetqd** [comment]
I am also using angular chart

[https://jtblin.github.io/angular-chart.js/]

I also tried to remove everything from the page and just have the progressbar and the same error occurred.

**Comment by marcgetqd** [comment]
Found out it was an issue with Angular Google Maps - had to upgrade past 2.x

https://github.com/angular-ui/angular-google-maps/issues/419
