### ISSUE TITLE
How to use it with multiple dynamic value for current scope variable

### ISSUE THREAD

**Issue by SanjanaJain23** [crisbeto/angular-svg-round-progressbar#87]
I am using this plugin in my project and the requirement is to display circular progress bar based on values which are fetched from JSON which is in an array. So please help me how can I use it so that data in JSON is populated dynamically from the array.

**Comment by aprendizfc** [comment]
have you tried:
<round-progress max="100" current="data.progress"></round-progress>

**Comment by SanjanaJain23** [comment]
Yes.. I tired like this and it is working. 

`<round-progress
                                                max="max"
                                                current="current"
                                                color="{{ getColor()}}"
                                                bgcolor="{{ bgColor}}"
                                                radius="{{ radius}}"
                                                semi="isSemi"
                                                rounded="rounded"
                                                stroke="{{ stroke}}"
                                                clockwise="clockwise"
                                                responsive="responsive"
                                                duration="{{ duration}}"
                                                animation="{{ currentAnimation}}"
                                                offset="{{ offset}}"
                                                animation-delay="{{ animationDelay}}"
                                                on-render="showPrecisseCurrent"
                                                ng-init="current = lead.percentile">
                                                </round-pssrogress>`

Thank you :)
