### ISSUE TITLE
Smooth animation while keeping in time

### ISSUE THREAD

**Issue by AppwareDev** [crisbeto/angular-svg-round-progressbar#92]
Hi, I have a pretty basic implementation of your module; countdown timer using interval every 1000 milliseconds which updates the `current` variable. I require a smooth animation so I have `duration= "1000"` however when I start the timer it takes 1000 milliseconds for the animation to begin and at the end of the timer I see zero before the progress bar has completed.

Is there someway to offset this behaviour so that the animation is smooth yet in time with the progress of the timer? I'm probably just being thick here but I can't figure it out!

Thanks

**Comment by crisbeto** [comment]
If you're using an easing function (which is the default), it's probably slowing down a lot towards the end. You can make it decrease consistently by setting `animation="linearEase"`.

**Comment by AppwareDev** [comment]
Thanks but I already have that property set.

**Comment by crisbeto** [comment]
Hmm, ok, in that case it might be easier with a code sample/codepen. Are you doing something like counting down to 1 minute by decrementing every 1000ms?

**Comment by AppwareDev** [comment]
Codepen: [http://codepen.io/remiappware/pen/AXZAVq](url) (I pinched the template from another issue to save time, sorry!)

Tap the timer to start/reset. As you'll see, the progress bar does not begin for 1000 milliseconds and ends 1000 milliseconds too late.

**Comment by crisbeto** [comment]
That's because it uses `$interval` (which is an Angular wrapper around `setInterval`) which won't fire the first time until 1 second after it was initiated.

**Comment by AppwareDev** [comment]
Of course. I knew it was something stupid. All sorted now, thanks and sorry for wasting your time!

**Comment by crisbeto** [comment]
No proble, you're welcome.
