### ISSUE TITLE
Changing Percent Complete Dynamically

### ISSUE THREAD

**Issue by stephenlane** [crisbeto/angular-svg-round-progressbar#94]
Hi There,

Just wondering is it possible to change the percent complete dynamically, trying it this way and it doesn't work

`  <div round-progress max="100" current=""{{mon_sleeps_p}}"" color="#45ccce" bgcolor="#eaeaea" radius="50" stroke="7" semi="false" rounded="false" clockwise="true" responsive="false" duration="800" animation="easeInOutQuart" animation-delay="0" offset="0"></div>`

Thanks,

Stephen

**Comment by crisbeto** [comment]
Yes, it's possible. You have a syntax error in the `current` attribute: you should remove the curly braces (`{{ }}`):

```html
<div round-progress max="100" current="mon_sleeps_p" color="#45ccce" bgcolor="#eaeaea" radius="50" stroke="7" semi="false" rounded="false" clockwise="true" responsive="false" duration="800" animation="easeInOutQuart" animation-delay="0" offset="0"></div>
```

**Comment by stephenlane** [comment]
Excellent thank you was driving me crazy :)

**Comment by crisbeto** [comment]
Also a tip: you don't have to specify all of the attributes. The example in the readme is only there to showcase them, but if they're not specified, they'll fall back to the defaults.

**Comment by stephenlane** [comment]
Excellent :) much appreciated
