### ISSUE TITLE
Show percentage

### ISSUE THREAD

**Issue by jesusmariocalleja** [crisbeto/angular-svg-round-progressbar#98]
Is it possible to show the % instead of NUMBER/TOTAL ?

**Comment by crisbeto** [comment]
Showing the text in the middle isn't (on purpose) a part of the module. You can refer to the demo to see how the text is positioned and you can use that to show a percentage instead.

**Comment by crisbeto** [comment]
I'll close the issue, but we can continue the discussion if you need any help.
