### ISSUE TITLE
Displaying percentage value inside the progress 

### ISSUE THREAD

**Issue by samuelmukoti** [crisbeto/angular-svg-round-progressbar#99]
Hi,

Thank you for this nice directive.  Any chance of displaying the percentage inside the progress?

**Comment by crisbeto** [comment]
This isn't a part of the module itself on purpose. [You can refer to this comment to see](https://github.com/crisbeto/angular-svg-round-progressbar/issues/55#issuecomment-173504646) how you can do it yourself.
